update
update

diff --git a/bin/nemotocRun b/bin/nemotocRun
--- a/bin/nemotocRun
+++ b/bin/nemotocRun
@@ -3,14 +3,16 @@
 while getopts ":c:" opt
 do 
     case $opt in 
-        c)
+        c )
         `which python` $OPTARG
         ;;
-        ?)
-        echo "unknown parameters"
+        \? )
+        echo "Invalid Option"
         exit 1;;
-        :)
-        echo "-c [configure file] $OPTARG"
-        ;;
+        : ) 
+        echo "Usage:nemotocRun -c [configure file]"
+        exit 1;;
         
-esac done
+esac 
+done
+shift $((OPTIND -1))
